// AUTO-GENERATED by scripts/genLocalConstants.ts — do not edit by hand.
// Input: deployer/deployments/deployments.json
// Deterministic addresses from deploying all protocols to a local (non-fork) anvil.
// constants.ts overlays these only when ERIS_LOCAL_DEPLOY=1.
import type { Address } from "viem";
import type { MarketLegs } from "./types.js";

// Canonical fingerprint of the source deployments.json (ADR 0016 §2). The backtest CLI
// compares it against the state dump manifest and, on mismatch, regenerates from the manifest's bundled deployments.
export const DEPLOYMENTS_FINGERPRINT = "sha256:4222255b6632b367d7dbf616e4650bc4f72e8f0d4355282f38d4547c1a83a909";

export type LocalDeployment = {
  CHAIN_ID: number;
  TOKENS: {
    WETH: { address: Address; decimals: number };
    USDC: { address: Address; decimals: number };
    WBTC?: { address: Address; decimals: number };
    DAI?: { address: Address; decimals: number };
  };
  USDC_VARIANTS: { native: Address; bridged: Address; usdt: Address };
  // Issue #27 (c): stables the deploy gave a market, so the scorer prices them from it instead of
  // asserting $1. Keyed by registry symbol. eUSD is not here -- its market comes from LIQUITY.
  STABLE_MARKETS?: Record<
    string,
    { pool: Address; stableIndex: number; quoteIndex: number }
  >;
  UNISWAP: {
    poolWethUsdc500: Address;
    swapRouter: Address;
    nonfungiblePositionManager: Address;
    quoterV2: Address;
    fee: number;
    tickSpacing: number;
  };
  MULTICALL3: Address;
  BALANCER: {
    vault: Address;
    queries: Address;
    pool: Address;
    poolId: `0x${string}`;
    tokens: Address[];
    usdcToken: Address;
    seedWethWei: bigint;
  };
  CURVE: { pool: Address; wethIndex: number; usdtIndex: number; usdcToken: Address };
  GMX: {
    RoleStore: Address; DataStore: Address; Oracle: Address; EventEmitter: Address;
    Router: Address; ExchangeRouter: Address; OrderHandler: Address; OrderVault: Address;
    LiquidationHandler: Address; Reader: Address; Config: Address;
  };
  GMX_MARKETS: { ETH_USD: Address };
  AAVE: {
    PoolAddressesProvider: Address; Pool: Address; AaveOracle: Address;
    AclAdmin: Address; AclManager: Address; PoolDataProvider: Address;
  };
  // ADR 0013: multi-asset market legs (WBTC etc.). Includes the WBTC leg if WBTC is in deployments.json.
  MARKET_LEGS?: MarketLegs;
  // Issue #38: present only when the deploy included the lst venue.
  LST?: {
    vault: Address;
    lstToken: Address;
    asset: Address;
    pool: Address;
    poolLstIndex: number;
    poolWethIndex: number;
    simulatedSecondsPerBlock: number;
    targetApyBps: number;
    withdrawalDelayBlocks: number;
    aaveAggregator?: Address;
    aaveAToken?: Address;
    aaveVariableDebtToken?: Address;
  };
  // Issue #39: present only when the deploy included the liquity venue.
  LIQUITY?: {
    troveManager: Address;
    borrowerOperations: Address;
    stabilityPool: Address;
    sortedTroves: Address;
    activePool: Address;
    defaultPool: Address;
    collSurplusPool: Address;
    gasPool: Address;
    hintHelpers: Address;
    priceFeed: Address;
    redemptionHelper?: Address;
    eusd: Address;
    lqtyToken: Address;
    lqtyStaking: Address;
    communityIssuance: Address;
    eusdUsdcPool?: Address;
    eusdIndex?: number;
    usdcIndex?: number;
    stable?: Address;
  };
};

export const LOCAL_DEPLOYMENT: LocalDeployment | null = {
  CHAIN_ID: 31337,
  TOKENS: {
    WETH: { address: "0x5FbDB2315678afecb367f032d93F642f64180aa3" as Address, decimals: 18 },
    USDC: { address: "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512" as Address, decimals: 6 },
    WBTC: { address: "0xa513E6E4b8f2a923D98304ec87F64353C4D5C853" as Address, decimals: 8 },
    DAI: { address: "0x5FC8d32690cc91D4c39d9d3abcBD16989F875707" as Address, decimals: 18 },
  },
  STABLE_MARKETS: {
    DAI: { pool: "0xD33d097DD5eE1cB4927632DD211c7981eda96319" as Address, stableIndex: 1, quoteIndex: 0 },
  },
  // Local uses a single USDC/USDT. native/bridged are the same USDC; usdt maps to USDT.
  USDC_VARIANTS: {
    native: "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512" as Address,
    bridged: "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512" as Address,
    usdt: "0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9" as Address,
  },
  UNISWAP: {
    poolWethUsdc500: "0xe35086d02782CEC7D20b1a164dE141aa39CEe723" as Address,
    swapRouter: "0x0B306BF915C4d645ff596e518fAf3F9669b97016" as Address,
    nonfungiblePositionManager: "0x9A676e781A523b5d0C0e43731313A708CB607508" as Address,
    quoterV2: "0x959922bE3CAee4b8Cd9a407cc3ac1C251C2007B1" as Address,
    // The deployer's WETH/USDC pool is fee=3000 (0.3%) / tickSpacing=60.
    fee: 3000,
    tickSpacing: 60,
  },
  MULTICALL3: "0x610178dA211FEF7D417bC0e6FeD39F05609AD788" as Address,
  BALANCER: {
    vault: "0x09635F643e140090A9A8Dcd712eD6285858ceBef" as Address,
    queries: "0x67d269191c92Caf3cD7723F116c85e6E9bf55933" as Address,
    pool: "0xf0D7de80A1C242fA3C738b083C422d65c6c7ABF1" as Address,
    poolId: "0xf0d7de80a1c242fa3c738b083c422d65c6c7abf1000200000000000000000000" as `0x${string}`,
    // The deployer pool is 2 tokens [WETH, USDC] (80/20). There is no USDT leg.
    tokens: ["0x5FbDB2315678afecb367f032d93F642f64180aa3" as Address, "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512" as Address],
    usdcToken: "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512" as Address,
    seedWethWei: 100_000_000_000_000_000_000n,
  },
  // Curve: twocrypto-ng's WETH/USDC crypto pool (uint256 index get_dy/exchange).
  // coin0=USDC(stable)=0, coin1=WETH=1. usdcToken is the pool's stable=USDC.
  CURVE: {
    pool: "0xd1891dD9DFF0784baa1dEb361dDFCAa5aE49cc6F" as Address,
    wethIndex: 1,
    usdtIndex: 0,
    usdcToken: "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512" as Address,
  },
  GMX: {
    RoleStore: "0x0000000000000000000000000000000000000000" as Address,
    DataStore: "0x0000000000000000000000000000000000000000" as Address,
    Oracle: "0x0000000000000000000000000000000000000000" as Address,
    EventEmitter: "0x0000000000000000000000000000000000000000" as Address,
    Router: "0x0000000000000000000000000000000000000000" as Address,
    ExchangeRouter: "0x0000000000000000000000000000000000000000" as Address,
    OrderHandler: "0x0000000000000000000000000000000000000000" as Address,
    OrderVault: "0x0000000000000000000000000000000000000000" as Address,
    LiquidationHandler: "0x0000000000000000000000000000000000000000" as Address,
    Reader: "0x0000000000000000000000000000000000000000" as Address,
    Config: "0x0000000000000000000000000000000000000000" as Address,
  },
  GMX_MARKETS: { ETH_USD: "0x0000000000000000000000000000000000000000" as Address },
  AAVE: {
    PoolAddressesProvider: "0xB0D4afd8879eD9F52b28595d31B441D079B2Ca07" as Address,
    Pool: "0x7B6fCB97Fc1B74e16CBe577054a4426d3487837C" as Address,
    AaveOracle: "0xfbC22278A96299D91d41C453234d97b4F5Eb9B2d" as Address,
    AclAdmin: "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266" as Address,
    AclManager: "0x4EE6eCAD1c2Dae9f525404De8555724e3c35d07B" as Address,
    PoolDataProvider: "0x5081a39b8A5f0E35a8D959395a630b68B74Dd30f" as Address,
  },
  // Issue #38: the LST venue (wstETH-style vault + LST/WETH stableswap-ng secondary market).
  LST: {
    vault: "0xD49a0e9A4CD5979aE36840f542D2d7f02C4817Be" as Address,
    lstToken: "0xD49a0e9A4CD5979aE36840f542D2d7f02C4817Be" as Address,
    asset: "0x5FbDB2315678afecb367f032d93F642f64180aa3" as Address,
    pool: "0x3d8bf8Fc25136DC4Bf6CF7c2ee688b9a66a480F3" as Address,
    poolLstIndex: 1,
    poolWethIndex: 0,
    simulatedSecondsPerBlock: 3600,
    targetApyBps: 300,
    withdrawalDelayBlocks: 24,
    aaveAggregator: "0x70bDA08DBe07363968e9EE53d899dFE48560605B" as Address,
    aaveAToken: "0xfB2C19FF34F419a02e4564e8Ce6A3448fAD93f8b" as Address,
    aaveVariableDebtToken: "0x555a114B12884781a975Fa45bDb4d3cC9ba1d640" as Address,
  },
  // Issue #39: Liquity V1 as the CDP stablecoin venue (eUSD). priceFeed is the adapter Liquity holds
  // forever, which each run repoints at its own PriceFeed -- not the run's feed itself.
  LIQUITY: {
    troveManager: "0xaB7B4c595d3cE8C85e16DA86630f2fc223B05057" as Address,
    borrowerOperations: "0x821f3361D454cc98b7555221A06Be563a7E2E0A6" as Address,
    stabilityPool: "0x045857BDEAE7C1c7252d611eB24eB55564198b4C" as Address,
    sortedTroves: "0xB06c856C8eaBd1d8321b687E188204C1018BC4E5" as Address,
    activePool: "0xAD523115cd35a8d4E60B3C0953E0E0ac10418309" as Address,
    defaultPool: "0x413b1AfCa96a3df5A686d8BFBF93d30688a7f7D9" as Address,
    collSurplusPool: "0x02df3a3F960393F5B349E40A599FEda91a7cc1A7" as Address,
    gasPool: "0x2b5A4e5493d4a54E717057B127cf0C000C876f9B" as Address,
    hintHelpers: "0x1780bCf4103D3F501463AD3414c7f4b654bb7aFd" as Address,
    priceFeed: "0x12Bcb546bC60fF39F1Adfc7cE4605d5Bd6a6A876" as Address,
    redemptionHelper: "0xe039608E695D21aB11675EBBA00261A0e750526c" as Address,
    eusd: "0xeF31027350Be2c7439C1b0BE022d49421488b72C" as Address,
    lqtyToken: "0xC66AB83418C20A65C3f8e83B3d11c8C3a6097b6F" as Address,
    lqtyStaking: "0x71089Ba41e478702e1904692385Be3972B2cBf9e" as Address,
    communityIssuance: "0x5133BBdfCCa3Eb4F739D599ee4eC45cBCD0E16c5" as Address,
    eusdUsdcPool: "0x4Bf20508953919be9691522ee74a7677c1a0a932" as Address,
    eusdIndex: 0,
    usdcIndex: 1,
    stable: "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512" as Address,
  },
  MARKET_LEGS: {
    uniswap: {
      WETH: { pool: "0xe35086d02782CEC7D20b1a164dE141aa39CEe723" as Address, fee: 3000, tickSpacing: 60 },
      WBTC: { pool: "0x1B99e1798C19F366b750819eDdfA27d77476cdaC" as Address, fee: 3000, tickSpacing: 60 },
    },
    balancer: {
      WETH: { poolId: "0xf0d7de80a1c242fa3c738b083c422d65c6c7abf1000200000000000000000000" as `0x${string}`, tokens: ["0x5FbDB2315678afecb367f032d93F642f64180aa3" as Address, "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512" as Address], stable: "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512" as Address },
      WBTC: { poolId: "0x1a7a3e29c3c4b3c858f2ded8be6ed51a07589ecf000200000000000000000001" as `0x${string}`, tokens: ["0xa513E6E4b8f2a923D98304ec87F64353C4D5C853" as Address, "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512" as Address], stable: "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512" as Address },
    },
    curve: {
      WETH: { pool: "0xd1891dD9DFF0784baa1dEb361dDFCAa5aE49cc6F" as Address, baseIndex: 1, quoteIndex: 0, stable: "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512" as Address },
      WBTC: { pool: "0xF2AdAad89d56D49C697B9907C7D66ef27d96f859" as Address, baseIndex: 1, quoteIndex: 0, stable: "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512" as Address },
    },
    gmx: {
      WETH: { market: "0x0000000000000000000000000000000000000000" as Address },
    },
    aave: {
      WETH: {},
      WBTC: {},
    },
  },
};
