// AUTO-GENERATED by scripts/genLocalConstants.ts — do not edit by hand.
// Input: /tmp/claude-1000/-home-haruki-git-eris-agent-simulator/e0a3ba3e-2de6-480d-9b2a-d6aadfe2830e/scratchpad/deployments-ascon.json
// Deterministic addresses from deploying all protocols to a local (non-fork) anvil.
// constants.ts overlays these only when ERIS_LOCAL_DEPLOY=1.
import type { Address } from "viem";
import type { MarketLegs } from "./types.js";

// Canonical fingerprint of the source deployments.json (ADR 0016 §2). The backtest CLI
// compares it against the state dump manifest and, on mismatch, regenerates from the manifest's bundled deployments.
export const DEPLOYMENTS_FINGERPRINT = "sha256:a0c0a5f343459d0f9904b1a2d13650cdaa9c1ef36f61a70ee55c644e5af31055";

export type LocalDeployment = {
  CHAIN_ID: number;
  TOKENS: {
    WETH: { address: Address; decimals: number };
    USDC: { address: Address; decimals: number };
    WBTC?: { address: Address; decimals: number };
    DAI?: { address: Address; decimals: number };
  };
  USDC_VARIANTS: { native: Address; bridged: Address; usdt: Address };
  // Issue #27 (c): stables the deploy gave a market, so the scorer prices them from it instead of
  // asserting $1. Keyed by registry symbol. eUSD is not here -- its market comes from LIQUITY.
  STABLE_MARKETS?: Record<
    string,
    { pool: Address; stableIndex: number; quoteIndex: number }
  >;
  UNISWAP: {
    poolWethUsdc500: Address;
    swapRouter: Address;
    nonfungiblePositionManager: Address;
    quoterV2: Address;
    fee: number;
    tickSpacing: number;
  };
  MULTICALL3: Address;
  BALANCER: {
    vault: Address;
    queries: Address;
    pool: Address;
    poolId: `0x${string}`;
    tokens: Address[];
    usdcToken: Address;
    seedWethWei: bigint;
  };
  CURVE: { pool: Address; wethIndex: number; usdtIndex: number; usdcToken: Address };
  GMX: {
    RoleStore: Address; DataStore: Address; Oracle: Address; EventEmitter: Address;
    Router: Address; ExchangeRouter: Address; OrderHandler: Address; OrderVault: Address;
    LiquidationHandler: Address; Reader: Address; Config: Address;
  };
  GMX_MARKETS: { ETH_USD: Address };
  AAVE: {
    PoolAddressesProvider: Address; Pool: Address; AaveOracle: Address;
    AclAdmin: Address; AclManager: Address; PoolDataProvider: Address;
  };
  // ADR 0013: multi-asset market legs (WBTC etc.). Includes the WBTC leg if WBTC is in deployments.json.
  MARKET_LEGS?: MarketLegs;
  // Issue #38: present only when the deploy included the lst venue.
  LST?: {
    vault: Address;
    lstToken: Address;
    asset: Address;
    pool: Address;
    poolLstIndex: number;
    poolWethIndex: number;
    simulatedSecondsPerBlock: number;
    targetApyBps: number;
    withdrawalDelayBlocks: number;
    aaveAggregator?: Address;
    aaveAToken?: Address;
    aaveVariableDebtToken?: Address;
  };
  // Issue #39: present only when the deploy included the liquity venue.
  LIQUITY?: {
    troveManager: Address;
    borrowerOperations: Address;
    stabilityPool: Address;
    sortedTroves: Address;
    activePool: Address;
    defaultPool: Address;
    collSurplusPool: Address;
    gasPool: Address;
    hintHelpers: Address;
    priceFeed: Address;
    redemptionHelper?: Address;
    eusd: Address;
    lqtyToken: Address;
    lqtyStaking: Address;
    communityIssuance: Address;
    eusdUsdcPool?: Address;
    eusdIndex?: number;
    usdcIndex?: number;
    stable?: Address;
  };
};

export const LOCAL_DEPLOYMENT: LocalDeployment | null = {
  CHAIN_ID: 31337,
  TOKENS: {
    WETH: { address: "0x4806ddDB48da9285EED230C907075861a50A75f4" as Address, decimals: 18 },
    USDC: { address: "0x04370d7F67549867eB93427B453FF5F6ceb0A27A" as Address, decimals: 6 },
    DAI: { address: "0xF02dd180B9a072c84C5e34207307c7cbD4Ec4D43" as Address, decimals: 18 },
  },
  STABLE_MARKETS: {
    DAI: { pool: "0x7Ae866B9dCEC864b237053edd6f67D99BFFBf6c6" as Address, stableIndex: 1, quoteIndex: 0 },
  },
  // Local uses a single USDC/USDT. native/bridged are the same USDC; usdt maps to USDT.
  USDC_VARIANTS: {
    native: "0x04370d7F67549867eB93427B453FF5F6ceb0A27A" as Address,
    bridged: "0x04370d7F67549867eB93427B453FF5F6ceb0A27A" as Address,
    usdt: "0x04370d7F67549867eB93427B453FF5F6ceb0A27A" as Address,
  },
  UNISWAP: {
    poolWethUsdc500: "0x24f7f1744a9fF6Da261bd6FCa8Ceda8cdbbCd73d" as Address,
    swapRouter: "0x0f958dC97eabC0774006E45781dCbCEaCBCBdF2f" as Address,
    nonfungiblePositionManager: "0xa7A0a6aC6d14f4965D4474bb269f290383e5642d" as Address,
    quoterV2: "0x9B7e0263A354329AA97eAc09A6843EC3191d93E8" as Address,
    // The deployer's WETH/USDC pool is fee=3000 (0.3%) / tickSpacing=60.
    fee: 3000,
    tickSpacing: 60,
  },
  MULTICALL3: "0x138dcaD3D08FdfC3C8652955b8c29DD02Ea070BC" as Address,
  BALANCER: {
    vault: "0x648Bff5787113E9930b9d033A65F0522b52486Bd" as Address,
    queries: "0x16fBf19Bb2429D2D93CB22646A7401E0D67b15eE" as Address,
    pool: "0x238A6a17807cfd8a5ccB231e43f8CC446ecB679d" as Address,
    poolId: "0x238a6a17807cfd8a5ccb231e43f8cc446ecb679d000200000000000000000000" as `0x${string}`,
    // The deployer pool is 2 tokens [WETH, USDC] (80/20). There is no USDT leg.
    tokens: ["0x04370d7F67549867eB93427B453FF5F6ceb0A27A" as Address, "0x4806ddDB48da9285EED230C907075861a50A75f4" as Address],
    usdcToken: "0x04370d7F67549867eB93427B453FF5F6ceb0A27A" as Address,
    seedWethWei: 100_000_000_000_000_000_000n,
  },
  // Curve: twocrypto-ng's WETH/USDC crypto pool (uint256 index get_dy/exchange).
  // coin0=USDC(stable)=0, coin1=WETH=1. usdcToken is the pool's stable=USDC.
  CURVE: {
    pool: "0x6339E9CeFeE6fFeef31A385d9f21E943C2BE5dAA" as Address,
    wethIndex: 1,
    usdtIndex: 0,
    usdcToken: "0x04370d7F67549867eB93427B453FF5F6ceb0A27A" as Address,
  },
  GMX: {
    RoleStore: "0xC5D2489102C896B9DE7F15CA774cDfF6280D4EF3" as Address,
    DataStore: "0xbA0F2E2Cfc4B4b8c3711A4bE3a41AEfB5F1628b8" as Address,
    Oracle: "0x44e78b4FEcfF638Fda37d737Bd08C3843007608B" as Address,
    EventEmitter: "0x37E4CA743F60F5bFa149B0A200e1fB425b8bA5CA" as Address,
    Router: "0x7c6F8b352B4f6844DdbdA01AdBEE825ec6C94649" as Address,
    ExchangeRouter: "0xaabD2617B6C594421A253b70B1FfA6D398E8fD32" as Address,
    OrderHandler: "0x409df769b749b9bc49E23ad4Fe059eaE8D7ca7Da" as Address,
    OrderVault: "0x4D7695fC1Bec599DAE86debDBBe84D34c07314Cc" as Address,
    LiquidationHandler: "0xeb452d09c16Ed9fC1726ee446c7F70b9763958Fa" as Address,
    Reader: "0xf7Df97313a987cE2951C7F7BE71f28Ad665EdC3C" as Address,
    Config: "0xe0959b5C089A6AecCc6C4948141232f3697EC132" as Address,
  },
  GMX_MARKETS: { ETH_USD: "0xa6bA738f27c1c05f591794aAc13836Fa6c10D0Fd" as Address },
  AAVE: {
    PoolAddressesProvider: "0x313147967b7E6753BE7D732A3a69C7a8832962Fc" as Address,
    Pool: "0x2978556fFBF5946f3A6e08174FCB29939206157F" as Address,
    AaveOracle: "0xc83C05e35DE2d621f1AB332ECe7b0F14a9f3F3c3" as Address,
    AclAdmin: "0x3d05E3979a2dB7E8980B3A5Aa0D535c442676fBF" as Address,
    AclManager: "0x2D79fb26DD50395B06bCCdF17D1F5fBF7E4dB538" as Address,
    PoolDataProvider: "0x28Cf22d66CbABbf622e00aBB140fF152C3FFF1D7" as Address,
  },
  // Issue #38: the LST venue (wstETH-style vault + LST/WETH stableswap-ng secondary market).
  LST: {
    vault: "0x1fE6c7635E1DeF53ad48D5CEf2293812c3186bC9" as Address,
    lstToken: "0x1fE6c7635E1DeF53ad48D5CEf2293812c3186bC9" as Address,
    asset: "0x4806ddDB48da9285EED230C907075861a50A75f4" as Address,
    pool: "0x1cEb5689331dCe15a369b53E18021EF82a08F1Ce" as Address,
    poolLstIndex: 1,
    poolWethIndex: 0,
    simulatedSecondsPerBlock: 3600,
    targetApyBps: 300,
    withdrawalDelayBlocks: 24,
    aaveAggregator: "0x92649D42A85D1E3Eb737D0e45eB0F12BA67DFf19" as Address,
    aaveAToken: "0xD2255a60e1741C1f589dCCd331B369AD37CeeB76" as Address,
    aaveVariableDebtToken: "0x098dA64fDCCFF6a9aEd6f5FaF869DAE13b8B5689" as Address,
  },
  // Issue #39: Liquity V1 as the CDP stablecoin venue (eUSD). priceFeed is the adapter Liquity holds
  // forever, which each run repoints at its own PriceFeed -- not the run's feed itself.
  LIQUITY: {
    troveManager: "0xf23A44330fBAC38373a8D746D95c7d9569b31D18" as Address,
    borrowerOperations: "0xAD8bd38E9863F90eF4a755FFE60778a1d7CBF530" as Address,
    stabilityPool: "0xcB6AC54Fa67cab9040168456c062A0B47a084F67" as Address,
    sortedTroves: "0x8e93c8c066842818D10AB518A224e729308ae2B4" as Address,
    activePool: "0x79351Bf621B2e7D1C67E08F3575123fB7daE7AB4" as Address,
    defaultPool: "0x4a30a3026B30E4B46dCA9Ede22f5e03e5365b662" as Address,
    collSurplusPool: "0x5AB2035Dafee869B9103Ed96d6E0AeF770064fb7" as Address,
    gasPool: "0x0cef2b8B05f4651c4674c03892fe8B1c2a7f77CA" as Address,
    hintHelpers: "0x2026283B8acB4419e325e639841B23c0dBb7153E" as Address,
    priceFeed: "0x0Ef27DF1F5d7B8Dfde6E92bc34f8b59C4D7f52DA" as Address,
    redemptionHelper: "0xa441111Ee25043d92130a8E7A3CdB37C94E5Ebf9" as Address,
    eusd: "0xdF2Fa95A51060FF34a9464B8E1A004Bd3fbb3845" as Address,
    lqtyToken: "0x5d09ccD6E6aD250E81d1D7AE70F5dA49f52f273F" as Address,
    lqtyStaking: "0xd1edeA127D1bd9FCA6d291dDF543E4d3DE9A27E4" as Address,
    communityIssuance: "0x580a815b04ebfb9CC2d5840046d0b31f3BEc469d" as Address,
    eusdUsdcPool: "0x5FD31a558e0A3c51fE1F18F5F2045bcEFda04d25" as Address,
    eusdIndex: 0,
    usdcIndex: 1,
    stable: "0x04370d7F67549867eB93427B453FF5F6ceb0A27A" as Address,
  },
  MARKET_LEGS: {
    uniswap: {
      WETH: { pool: "0x24f7f1744a9fF6Da261bd6FCa8Ceda8cdbbCd73d" as Address, fee: 3000, tickSpacing: 60 },
    },
    balancer: {
      WETH: { poolId: "0x238a6a17807cfd8a5ccb231e43f8cc446ecb679d000200000000000000000000" as `0x${string}`, tokens: ["0x04370d7F67549867eB93427B453FF5F6ceb0A27A" as Address, "0x4806ddDB48da9285EED230C907075861a50A75f4" as Address], stable: "0x04370d7F67549867eB93427B453FF5F6ceb0A27A" as Address },
    },
    curve: {
      WETH: { pool: "0x6339E9CeFeE6fFeef31A385d9f21E943C2BE5dAA" as Address, baseIndex: 1, quoteIndex: 0, stable: "0x04370d7F67549867eB93427B453FF5F6ceb0A27A" as Address },
    },
    gmx: {
      WETH: { market: "0xa6bA738f27c1c05f591794aAc13836Fa6c10D0Fd" as Address },
    },
    aave: {
      WETH: {},
    },
  },
};
